# Generated by Django 4.2.1 on 2023-06-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('captura_data_hora', models.DateTimeField()),
                ('registro_data_hora', models.DateTimeField()),
                ('envio_tentativa_data_hora', models.DateTimeField()),
                ('envio_data_hora', models.DateTimeField()),
                ('placa', models.CharField(max_length=255)),
                ('placa_tipo', models.CharField(max_length=25)),
                ('placa_totalmente_reconhecida', models.BooleanField()),
                ('sentido', models.CharField(max_length=255)),
                ('camera_nome', models.CharField(max_length=255)),
                ('camera_codigo', models.CharField(max_length=255)),
                ('veiculo_tipo', models.CharField(max_length=50)),
                ('veiculo_cor', models.CharField(max_length=50)),
                ('velocidade', models.CharField(max_length=50)),
                ('faixa', models.CharField(max_length=10)),
                ('ultimo_enviado_id', models.IntegerField()),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('status_cpu', models.TextField()),
                ('status_ram', models.TextField()),
                ('status_disco', models.TextField()),
                ('status_rede', models.TextField()),
                ('ping_sefaz', models.BooleanField()),
                ('ping_camera', models.BooleanField()),
                ('camera_latitude', models.CharField(max_length=255)),
                ('camera_longitude', models.CharField(max_length=255)),
                ('camera_endereco', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
