-- AlterTable
ALTER TABLE "telemetrias" ALTER COLUMN "captura_data_hora" DROP NOT NULL,
ALTER COLUMN "registro_data_hora" DROP NOT NULL,
ALTER COLUMN "envio_tentativa_data_hora" DROP NOT NULL,
ALTER COLUMN "envio_data_hora" DROP NOT NULL,
ALTER COLUMN "placa" DROP NOT NULL,
ALTER COLUMN "placa_tipo" DROP NOT NULL,
ALTER COLUMN "placa_totalmente_reconhecida" DROP NOT NULL,
ALTER COLUMN "sentido" DROP NOT NULL,
ALTER COLUMN "camera_nome" DROP NOT NULL,
ALTER COLUMN "camera_codigo" DROP NOT NULL,
ALTER COLUMN "veiculo_tipo" DROP NOT NULL,
ALTER COLUMN "veiculo_cor" DROP NOT NULL,
ALTER COLUMN "velocidade" DROP NOT NULL,
ALTER COLUMN "faixa" DROP NOT NULL,
ALTER COLUMN "arquivo_nome" DROP NOT NULL,
ALTER COLUMN "status_cpu" DROP NOT NULL,
ALTER COLUMN "status_ram" DROP NOT NULL,
ALTER COLUMN "status_disco" DROP NOT NULL,
ALTER COLUMN "status_rede" DROP NOT NULL,
ALTER COLUMN "ping_sefaz" DROP NOT NULL,
ALTER COLUMN "ping_camera" DROP NOT NULL,
ALTER COLUMN "camera_latitude" DROP NOT NULL,
ALTER COLUMN "camera_longitude" DROP NOT NULL,
ALTER COLUMN "camera_endereco" DROP NOT NULL;
